const BOOK_SHORTENINGS: Record<string, string> = {
  genesis: "Gen",
  exodus: "Exod",
  leviticus: "Lev",
  numbers: "Num",
  deuteronomy: "Deut",
  joshua: "Josh",
  judges: "Judg",
  ruth: "Ruth",
  "1 samuel": "1 Sam",
  "2 samuel": "2 Sam",
  "1 kings": "1 Kgs",
  "2 kings": "2 Kgs",
  "1 chronicles": "1 Chr",
  "2 chronicles": "2 Chr",
  ezra: "Ezra",
  nehemiah: "Neh",
  esther: "Esth",
  job: "Job",
  psalm: "Ps",
  proverbs: "Prov",
  ecclesiastes: "Eccl",
  "song of solomon": "Song",
  isaiah: "Isa",
  jeremiah: "Jer",
  lamentations: "Lam",
  ezekiel: "Ezek",
  daniel: "Dan",
  hosea: "Hos",
  joel: "Joel",
  amos: "Amos",
  obadiah: "Obad",
  jonah: "Jonah",
  micah: "Mic",
  nahum: "Nah",
  habakkuk: "Hab",
  zephaniah: "Zeph",
  haggai: "Hag",
  zechariah: "Zech",
  malachi: "Mal",
  matthew: "Matt",
  mark: "Mark",
  luke: "Luke",
  john: "John",
  acts: "Acts",
  romans: "Rom",
  "1 corinthians": "1 Cor",
  "2 corinthians": "2 Cor",
  galatians: "Gal",
  ephesians: "Eph",
  philippians: "Phil",
  colossians: "Col",
  "1 thessalonians": "1 Thess",
  "2 thessalonians": "2 Thess",
  "1 timothy": "1 Tim",
  "2 timothy": "2 Tim",
  titus: "Titus",
  philemon: "Phlm",
  hebrews: "Heb",
  james: "James",
  "1 peter": "1 Pet",
  "2 peter": "2 Pet",
  "1 john": "1 Jn",
  "2 john": "2 Jn",
  "3 john": "3 Jn",
  jude: "Jude",
  revelation: "Rev",
};

export function shortenBookName(name: string): string {
  const key = name.toLowerCase().trim();
  return BOOK_SHORTENINGS[key] || name;
}
